apiVersion: v1
kind: Service
metadata:
  name: blood-helper-backend
  namespace: blood-helper
  labels:
    app: blood-helper-backend
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app: blood-helper-backend
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
